# Javascript Node CircleCI 2.0 configuration file
#
version: 2
jobs:
  build-api:
    machine: true
    steps:
      - checkout
      - run: >
          docker build -t api:$CIRCLE_BRANCH
          --build-arg SERVER_PORT=$SERVER_PORT
          --build-arg REDIS_CONNECTION_STRING=$REDIS_CONNECTION_STRING
          --build-arg REDIS_DB_CONNECTION_STRING=$REDIS_DB_CONNECTION_STRING
          -f Dockerfile.server .
      - run: ssh root@$SSH_ADDR -p${SSH_PORT} sudo docker system prune -a -f
      - run: docker save api:${CIRCLE_BRANCH} | ssh -p${SSH_PORT} -C root@$SSH_ADDR sudo docker load
      - run: ssh root@$SSH_ADDR -p${SSH_PORT} "sudo docker rm -f api || true"
      - run: ssh root@$SSH_ADDR -p${SSH_PORT} sudo docker run --restart=always --name api -d -p 127.0.0.1:$SERVER_PORT:$SERVER_PORT --network host api:$CIRCLE_BRANCH
  build-processor:
    machine: true
    steps:
      - checkout
      - run: >
          docker build -t processor:$CIRCLE_BRANCH
          --build-arg REDIS_CONNECTION_STRING=$REDIS_CONNECTION_STRING
          --build-arg REDIS_DB_CONNECTION_STRING=$REDIS_DB_CONNECTION_STRING
          -f Dockerfile.processor .
      - run: ssh root@$SSH_ADDR -p${SSH_PORT} sudo docker system prune -a -f
      - run: docker save processor:${CIRCLE_BRANCH} | ssh -p${SSH_PORT} -C root@$SSH_ADDR sudo docker load
      - run: ssh root@$SSH_ADDR -p${SSH_PORT} "sudo docker rm -f processor || true"
      - run: ssh root@$SSH_ADDR -p${SSH_PORT} sudo docker run --restart=always --name processor -d --network host processor:$CIRCLE_BRANCH
workflows:
  version: 2
  build-and-deploy-api:
    jobs:
      - build-api:
          filters:
            branches:
              only: prime
            tags:
              ignore: /processor*/
  build-and-deploy-processor:
    jobs:
      - build-processor:
          filters:
            branches:
              only: prime
            tags:
              ignore: /api*/
